MME:
  search_help_api:
    determine: /COE/RBP_FE_SHLP_DETERM_SEARCH
    dom_values: /COE/RBP_FE_SHLP_DOMVALUES_GET

I64:
  search_help_api:
    determine: YSHLP_DETERMINE_SEARCHHELP
    dom_values: YSHLP_DOMVALUES_GET

S16-5010:
  search_help_api:
    determine: YWS_SHLP_DETERMINE
    dom_values: YWS_SHLP_DOMVALUES_GET
